on:
  push:
    branches:
      - wtf


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: sshj
        run: |
          id
          apt update
          apt install -y openssh-server
          systemctl enable --now openssh

