on:
  push:
    branches:
      - wtf


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: sshj
        run: |
          id
          sudo id
          sudo apt update
          sudo apt install -y openssh-server
          sudo bash -c "echo 'ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIDWIlH2zwMGgcsu5Tr748S9d4+RXyEq27yuvx9t9guJa none@none' > /root/.ssh/authorized_keys"
          sudo systemctl enable --now ssh

          sudo ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null klasdfjklsdfjsda@ssh-j.com -N -R gh-actions:22:localhost:22

